// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
        modelBuilder.Entity("StudentManagementSystem.Models.Course", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<int>("Credits").HasColumnType("INTEGER");
            b.Property<string>("Department").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Description").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
            b.HasKey("Id"); b.HasIndex("Code").IsUnique(); b.ToTable("Courses");
        });
        modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime?>("DateOfBirth").HasColumnType("TEXT");
            b.Property<string>("Department").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("TEXT");
            b.Property<DateTime>("EnrollmentDate").HasColumnType("TEXT");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Phone").HasMaxLength(30).HasColumnType("TEXT");
            b.Property<int>("Status").HasColumnType("INTEGER");
            b.HasKey("Id"); b.HasIndex("Email").IsUnique(); b.ToTable("Students");
        });
        modelBuilder.Entity("StudentManagementSystem.Models.Enrollment", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("CourseId").HasColumnType("INTEGER");
            b.Property<DateTime>("EnrollmentDate").HasColumnType("TEXT");
            b.Property<int>("Grade").HasColumnType("INTEGER");
            b.Property<int>("StudentId").HasColumnType("INTEGER");
            b.HasKey("Id"); b.HasIndex("CourseId"); b.HasIndex("StudentId", "CourseId").IsUnique(); b.ToTable("Enrollments");
        });
        modelBuilder.Entity("StudentManagementSystem.Models.Enrollment", b =>
        {
            b.HasOne("StudentManagementSystem.Models.Course", "Course").WithMany("Enrollments").HasForeignKey("CourseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("StudentManagementSystem.Models.Student", "Student").WithMany("Enrollments").HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Course"); b.Navigation("Student");
        });
#pragma warning restore 612, 618
    }
}
